### ISSUE TITLE
Investigar como solucionar el borrado de caché

### ISSUE THREAD

**Issue by MariaIrma** [julioingsist/facturacion#139]
Se debe investigar como solucionar el problema de la caché para producción.

**Comment by julioingsist** [comment]
Esto lo haré cuando se suba el proyecto al servidor. Por mientras hay que seguir recargando cache.

**Comment by MariaIrma** [comment]
Perfecto @julioingsist

**Comment by MariaIrma** [comment]
Este pendiente se realizará cuando estemos en producción, evitaremos que el cliente necesite estar recargando caché, para esto se deben versionar los archivos js, al subirse en producción se debe indicar porque archivo ir.

**Comment by MariaIrma** [comment]
Este pendiente se realizará cuando estemos en producción, evitaremos que el cliente necesite estar recargando caché, para esto se deben versionar los archivos js, al subirse en producción se debe indicar porque archivo ir. @julioingsist , @JosePicos
