### ISSUE TITLE
Borrado lógico o borrado físico

### ISSUE THREAD

**Issue by MariaIrma** [julioingsist/facturacion#146]
Creen conveniente hacer un borrado físico del producto(Así se realiza actualmente).

**Comment by julioingsist** [comment]
¿Como es el borrado lógico? @MariaIrma

**Comment by MariaIrma** [comment]
Que solo e borre de la vista de la página, pero que de la base de datos no se borre, tener como un historial de los productos registrados.

**Comment by julioingsist** [comment]
y si lo dan de alta otra vez? no se estaría repitiendo información? creo que es mejor ponerles estatus. Que opinas @JosePicos ?

**Comment by MariaIrma** [comment]
Se maneja el borrado lógico en lugar del físico, agregando estatus vigente y cancelado a catálogos de productos y al de clientes.
